apps:
  - name: rework-frontend-api
    environment: production
    codebase: rework-frontend
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    container:
      image:
        repository: osuakatsuki/rework-frontend
        tag: latest
      port: 80
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 300m
          memory: 250Mi
        requests:
          cpu: 75m
          memory: 150Mi
      env:
        - name: APP_COMPONENT
          value: api
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80
